### ISSUE TITLE
Allow defining actions in terms of other actions

### ISSUE THREAD

**Issue by StandingPadAnimations** [Moo-Ack-Productions/bpy-build#15]
Right now, every action requires an individual script, which results in actions that are made from “master” scripts. Although this works fine, it can make debugging a nightmare if these scripts don't propagate errors (see #14).

In order to make things easier for developers, a `subactions` variable will be added as an option for actions, and may look something like this (using translation actions in MCprep as an example):
```yaml
build_actions:
  translate:
    subactions: 
      - build_pot
  	build_pot: 
    	script: "dev.py"
```
