### ISSUE TITLE
Include source and build paths vars in run scripts

### ISSUE THREAD

**Issue by TheDuckCow** [Moo-Ack-Productions/bpy-build#7]
This is coming back to the thing I keep mentioning which is the slowest part of trying to follow test driven development: running tests often is painful, as it takes several minutes to just put the addons in place. With the old system, all installs with the fast option would happen in less than 2 seconds.

In my experience and in doing some testing today, the real crux of the problem is a) the large size of blend files and b) the sheer number of (resource pack image) files being created for the zip. No matter what we do, zipping and unzipping all those files will be slow.

My proposal:

- In MCprep, we create a "fast" option that looks like this; this already works quite nicely and runs pretty fast. Thus bypasses the entire time spent on compressing and extracting the resources folder.
```yaml
build_actions:
  default: 
    script: "action-scripts/default.py"
  dev: 
    script: "action-scripts/dev.py"
  fast:
    script: "action-scripts/dev.py"
    ignore_filters: 
      - "*.blend"
      - "MCprep_resources"
```
- Then in bpy build, create a mechanism for "hooks" to be searched for and called from action-scripts, including "pre_removal" and "post_extract" (or whatever names you find best). These would be methods inside an action script which would have args for the source and target path for a single install. These functions, if found, would be called for each action during the corresponding spot.
- Then in MCprep's repo, we could then create an mcprep script under the action-scripts folder (in the MCprep repo) for the fast option (fast.py) which for the first hook (pre deleting existing install) would just move the MCprep_resources to a temp location, and then in the post_extract hook would move it back.

This is probably the simplest thing we could do and, from my standpoint, would be the #1 time saver pretty quickly while doing testing and PR reviews.

Let me know what you think @StandingPadAnimations! Open to other suggestions
